name: "Docker Compose Command"
author: blag
description: "Run docker-compose within GitHub Actions"
inputs:
    cli-args:
        description: "Command line arguments for docker-compose"
        required: true

branding:
    icon: "terminal"
    color: blue
runs:
    using: "docker"
    image: "docker://blag/action-docker-compose:latest"
    args:
        - ${{ inputs.cli-args }}
