name: Build docker image

permissions:
    contents: read

on: [push]

jobs:
    build-action:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                # The docker official image only has amd64 and arm64/v8
                platform: ["linux/amd64"]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            # https://github.com/docker/setup-qemu-action
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            # https://github.com/docker/setup-buildx-action
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Build action image
              run: make docker-build
              env:
                DOCKER_BUILDKIT: 1
                PLATFORM: ${{ matrix.platform }}
