name: check action works

permissions:
    contents: read

on: [push]

jobs:
    check:
        name: Test the action
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: fetch the version
              uses: blag/action-docker-compose@latest
              with:
                  cli-args: "--version"
            - name: try to pull an image
              uses: blag/action-docker-compose@latest
              with:
                  cli-args: "-f .github/data/docker-compose-latest.test.yml pull"
            - name: try to compose up
              uses: blag/action-docker-compose@latest
              with:
                  cli-args: "-f .github/data/docker-compose-latest.test.yml up --exit-code-from=sut --abort-on-container-exit"
            - name: try to compose down
              uses: blag/action-docker-compose@latest
              with:
                  cli-args: "-f .github/data/docker-compose-latest.test.yml down"
